default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "OwnFont.xcodeproj",
      profile_name: "OwnFont AppStore",
      profile_uuid: ENV["PROFILE_UUID"],
      code_sign_identity: "Apple Distribution"
    )

    increment_build_number(
      build_number: ENV["BUILD_NUMBER"],
      xcodeproj: "OwnFont.xcodeproj"
    )

    build_app(
      project: "OwnFont.xcodeproj",
      scheme: "OwnFont",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.siro.OwnFont" => "OwnFont AppStore"
        }
      }
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_API_KEY_ID"],
      issuer_id: ENV["ASC_API_ISSUER_ID"],
      key_content: ENV["ASC_API_KEY_CONTENT"]
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
